#boringssl
SET_TARGET_PROPERTIES(crypto  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(aes  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(stack  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(lhash  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(err  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(base64  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(bytestring  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(pool  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(bio_decrepit  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(blowfish  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(cipher  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(rc4  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(conf  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(chacha  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(poly1305  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(curve25519  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(buf  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(bn  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(bio  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(bssl  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(obj  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(asn1  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(engine  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(dh  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(dsa  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(rsa  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(ec  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(ecdh  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(ecdsa  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(cmac  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(evp  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(hkdf  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(pem  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(x509  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(x509v3  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(cast  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(pkcs8_lib  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(ssl  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(decrepit  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(des  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(des_decrepit  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(dh_decrepit  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(digest  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(dsa_decrepit  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(evp_decrepit  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(hmac  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(md4  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(md5  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(modes  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(obj_decrepit  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(rand  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(rc4_decrepit  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(ripemd_decrepit  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(rsa_decrepit  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(sha  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(ssl_decrepit  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(x509_decrepit  PROPERTIES FOLDER "thirdparty/boringssl")
SET_TARGET_PROPERTIES(xts  PROPERTIES FOLDER "thirdparty/boringssl")

SET_TARGET_PROPERTIES(gflags_static PROPERTIES FOLDER "thirdparty/gflags")
SET_TARGET_PROPERTIES(gflags_nothreads_static PROPERTIES FOLDER "thirdparty/gflags")

SET_TARGET_PROPERTIES(zlibstatic PROPERTIES FOLDER "thirdparty/zlib")
SET_TARGET_PROPERTIES(zlib PROPERTIES FOLDER "thirdparty/zlib")

SET_TARGET_PROPERTIES(gtest PROPERTIES FOLDER "thirdparty/gtest")
# SET_TARGET_PROPERTIES(gtest_main PROPERTIES FOLDER "thirdparty/gtest")

SET_TARGET_PROPERTIES(cares PROPERTIES FOLDER "thirdparty/grpc")
SET_TARGET_PROPERTIES(gpr PROPERTIES FOLDER "thirdparty/grpc")
SET_TARGET_PROPERTIES(grpc PROPERTIES FOLDER "thirdparty/grpc")
SET_TARGET_PROPERTIES(grpc_cronet PROPERTIES FOLDER "thirdparty/grpc")
SET_TARGET_PROPERTIES(grpc_unsecure PROPERTIES FOLDER "thirdparty/grpc")
SET_TARGET_PROPERTIES(grpc++ PROPERTIES FOLDER "thirdparty/grpc")
SET_TARGET_PROPERTIES(grpc++_cronet PROPERTIES FOLDER "thirdparty/grpc")
SET_TARGET_PROPERTIES(grpc++_unsecure PROPERTIES FOLDER "thirdparty/grpc")
SET_TARGET_PROPERTIES(grpc_cpp_plugin PROPERTIES FOLDER "thirdparty/grpc")
SET_TARGET_PROPERTIES(grpc_plugin_support PROPERTIES FOLDER "thirdparty/grpc")

SET_TARGET_PROPERTIES(libprotobuf PROPERTIES FOLDER "thirdparty/protobuf")
SET_TARGET_PROPERTIES(libprotobuf-lite PROPERTIES FOLDER "thirdparty/protobuf")
IF(NOT IOS AND NOT ANDROID)
SET_TARGET_PROPERTIES(js_embed PROPERTIES FOLDER "thirdparty/protobuf")
SET_TARGET_PROPERTIES(libprotoc PROPERTIES FOLDER "thirdparty/protobuf")
SET_TARGET_PROPERTIES(protoc PROPERTIES FOLDER "thirdparty/protobuf")
ENDIF()